### PR TITLE
Air Assist plugin support 

### PR DESCRIPTION
**Pull request by jpirnay**
Basic Routines to introduce air assist support. By default there are just two basic methods available (alert and intrinsic gcode), but they can be extended by additional plugins.

### CODE REVIEW

**Comment by tatarize** [comment]
This should probably allow for plugins to trigger and toggle the coolant, probably via "air_assist" and "water_pump" signals.

**Comment by tatarize** [comment]
```python
ERROR: test_spoolerjob (test_spooler.TestSpooler)
Test spooler job
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/meerk40t/meerk40t/test/test_spooler.py", line 14, in test_spoolerjob
    kernel = bootstrap.bootstrap()
  File "/home/runner/work/meerk40t/meerk40t/test/bootstrap.py", line 51, in bootstrap
    kernel()
  File "/home/runner/work/meerk40t/meerk40t/meerk40t/kernel/kernel.py", line 1085, in __call__
    self.set_kernel_lifecycle(self, LIFECYCLE_KERNEL_POSTMAIN)
  File "/home/runner/work/meerk40t/meerk40t/meerk40t/kernel/kernel.py", line 682, in set_kernel_lifecycle
    plugin(kernel, "preboot")
  File "/home/runner/work/meerk40t/meerk40t/meerk40t/grbl/plugin.py", line 233, in plugin
    kernel.root(f"service device start -p {d} {suffix}\n")
  File "/home/runner/work/meerk40t/meerk40t/meerk40t/kernel/context.py", line 32, in __call__
    return self._kernel.console(data)
  File "/home/runner/work/meerk40t/meerk40t/meerk40t/kernel/kernel.py", line 2161, in console
    self._console_parse(command, channel=self._console_channel)
  File "/home/runner/work/meerk40t/meerk40t/meerk40t/kernel/kernel.py", line 2208, in _console_parse
    data, remainder, input_type = funct(
  File "/home/runner/work/meerk40t/meerk40t/meerk40t/kernel/functions.py", line 279, in inner
    returned = func(command=command, channel=channel, **ik, **kwargs)
  File "/home/runner/work/meerk40t/meerk40t/meerk40t/kernel/kernel.py", line 2951, in service_init
    service = provider(self, service_path)
  File "/home/runner/work/meerk40t/meerk40t/meerk40t/grbl/device.py", line 421, in __init__
    "dynamic": self.kernel.root.coolant.coolant_choice_helper(self),
AttributeError: 'Context' object has no attribute 'coolant'
```

Test failure is legit.

**Comment by FelixEL** [comment]
Why this feature has been abandoned?

**Comment by tatarize** [comment]
> Why this feature has been abandoned?

I think there was only like Ruida that allowed directly configured air. The rest would be controlled with other signals. This wasn't bad but I'm not sure how overall useful it would be.

**Comment by FelixEL** [comment]
> > Why this feature has been abandoned?
> 
> I think there was only like Ruida that allowed directly configured air. The rest would be controlled with other signals. This wasn't bad but I'm not sure how overall useful it would be.

Is a very valuable feature. In diode lasers engraving is done without air assist and cutting is done with air assist enabled. So automating this automatic switchover would bring massive value.

There are machines like **Sculpfun s30** which can enable air assist with M8/M9 commands. I'm working on the feature limited only to GRBL on my fork, based on awesome  work of @jpirnay . I will be able to test it on my GRBL machine if successful.

I just found this project and first I have to dig into the code base but it is COOL!

**Comment by jpirnay** [comment]
This is a thorn in my side and I need to pick it up. There's a more modern scaffold but without the real implementation in: https://github.com/jpirnay/meerk40t-airassist-mqtt
I will look at it again in the next couple of days.

**Comment by Sophist-UK** [comment]
Is there a way to have programmable Air Assist support for a m2 nano i.e. by using a spare port on the board and building some sort of relay box?

**Comment by tiger12506** [comment]
> Is there a way to have programmable Air Assist support for a m2 nano i.e. by using a spare port on the board and building some sort of relay box?

paiin was very interested in making that happen at one time. IIRC, best approach available would have been a hardware monitor of the serial chip to catch certain commands ignored by the m2nano.
In short, not really feasible.

**Comment by jpirnay** [comment]
I am working on a rest-api / mqtt plugin, that will allow to switch on/off a smart plugs like tasmota, shelly or espurna based plugs. Put that in front of a small aquarium pump and you are good to go

**Pull request closed without merging**
