### PR TITLE
Basic check for updates

### PR DESCRIPTION
**Pull request by Sophist-UK**
1. New Preference for checking for beta versions
2. Checks for beta if above setting checked or currently (temporarily) on a beta.

To-Do:
3. GUI ability to check for updates and report new version
4. GUI automated periodic (daily) check for new version, weekly reminders of previously reported new version
5. Download new version(s) if executable, and executable directory is writeable and new versions not already downloaded (with correct size).

### CODE REVIEW

**Comment by tatarize** [comment]
I might put the preference choice element in the updater script. The choice items will append if they have the same name (I think, might be an 0.8.0 change). So you could store everything in updater.py. But that all seems by definition harmless. 

#73

**Review by tatarize — APPROVED** [review]

**Comment by Sophist-UK** [comment]
It's a work in progress. Still neds a GUI option (pretty much coded) and an automated check option (in progress) and download functionality (To do)./

**Comment by Sophist-UK** [comment]
At present we cannot (AFAIK):

a. Put the GUI stuff associated with the updater (i.e. menus) into the plugin file.
b. Put the preferences into the plugin file (and have them appear in the Preferences window).

**Comment by tatarize** [comment]
0.8.0 can have gui stuff added. Though currently the mechanism is a bit cumbersome if you want to to have gui and non-gui features. These are currently being shoved into main as a second plugin dependant on the other plugins since requiring wx won't work well out of the gate. But, if you want to include some menu option stuff that seems to sort of work in 0.8.0. Or at least all the menus are currently dynamic for windows and panes.

**Comment by Sophist-UK** [comment]
Ok - let's merge this. But I am hopeful that the final version I am still working on will be elegant.

**Pull request merged**
