### PR TITLE
Change Ribbonbar Library

### PR DESCRIPTION
**Pull request by jpirnay**
a) Replace the wxWidget based RibbonBar with wx.lib.agw.RibbonBar
b) Some new align commands as testcase: 
```
align bedleft
align bedright
align bed top
align bedbottom
align bedcenter
```
These commands will be used if you click on the align buttons with the right mousebutton:
aligning

Tests needed on OSX and Linux

### CODE REVIEW

**Comment by jpirnay** [comment]
Issues
- [ ] Darkmode on Linux only partially working

**Comment by tatarize** [comment]
The merging fixes the conflict, far easier doing that than undoing things. If you use pycharm just merge main into the ribbonbar branch. I recall last time you just booted the branch when it conflicted. You select merge and then hit the arrows which version should be kept.

**Comment by jpirnay** [comment]
Darkmode seems to work on Linux, no clue for Darwin
grafik

**Review by tatarize — APPROVED** [review]

**Comment by jpirnay** [comment]
Will wait for final tests

**Review by tatarize — APPROVED** [review]

**Pull request merged**
