### PR TITLE
Help takes you to Wiki not repo.

### PR DESCRIPTION
**Pull request by Sophist-UK**
Note: Github has "kindly"(!!) changed from ISOxxxx to UTF-8 - hence changes for lines containing accented characters.

### CODE REVIEW

**Comment by tatarize** [comment]
There's a stable branch. That's easier to PR to since master requires an approving review. And Joe is pretty diligent in his QA duties. https://github.com/meerk40t/meerk40t/tree/0.6.18 

I'll add in your change to the 0.7.0 and 0.6.x code bases. Though PRs to the stable or experimental branches are a lot easier to just merge.

**Comment by tatarize** [comment]
Rebased the commit. Added a few spots, the ? on the ribbon bar goes to the wiki. The wiki takes over ID_HELP which matters for some mac stuff and some internal wxPython things. I'll port the same changes over to 0.7.0.

**Comment by tatarize** [comment]
https://github.com/meerk40t/meerk40t/releases/tag/0.6.18-beta2

Should have that live. Waiting for QA review on #316 to put it in the full release.

**Comment by Sophist-UK** [comment]
Thanks. You may have seen I have been working on the Wiki.

**Comment by tatarize** [comment]
This is now live in version 0.6.18. With some additional tweaks in 0.7.0 on top of those.

**Pull request closed without merging**
