### PR TITLE
Correct Mouse Cursor Issues

### PR DESCRIPTION
**Pull request by tatarize**

### CODE REVIEW

**Comment by tatarize** [comment]
I did some more work on this but something outside the code like the redraw routine or something is resetting the mouse. Makes it hard to diagnose. I recall there was a reason I gave up on this before.

**Comment by Sophist-UK** [comment]
I tried again to track this down - but still failed. I am wondering whether it is:

a. Something to do with the Window Refresh/Update buffering
b. A bug in the wxPython code.
c. Another example of a global `except: pass`.

**Review by tatarize — COMMENTED** [review]
Seems fine now.

**Review by Sophist-UK — APPROVED** [review]
I haven't tested it, but a code review looks OK (from my limited understanding of how MK works).

**Pull request merged**
