### PR TITLE
Correct Ruidacontrol settings update

### PR DESCRIPTION
**Pull request by tatarize**

### CODE REVIEW

**Comment by Sophist-UK** [comment]
We need to push out this fix in at least a beta reasonably quickly.

**Comment by tatarize** [comment]
Double checked and works fine, lemme try one test to make sure the code I have was broken in the older version (it should be).

**Comment by tatarize** [comment]
Confirmed issue exists and was fixed. We could also bump up the version to 5001 and push new full version or whatever.

There's literally nothing we've added that was remotely scary.

**Comment by tatarize** [comment]
@Sophist-UK I say we merge this and #837. And release another version. No need to flag it beta since it's the same code. Might build the linux stuff correctly this time.

**Comment by Sophist-UK** [comment]
Ok. I guess it won't hurt to push out a new full version so soon after the previous one to fix this.

**Comment by tatarize** [comment]
Well, it's just another release in the 5000 series. Without starting a new beta sequence or whatever. Nothing here is concerning and might as well fix that thing we wanted fixed correctly. -- Go ahead and do all 3 steps. Approve/merge, approve/merge, and release the 5001 version.

**Review by Sophist-UK — APPROVED** [review]

**Pull request merged**
