### PR TITLE
Improve Cut Inner First performance

### PR DESCRIPTION
**Pull request by Sophist-UK**

### CODE REVIEW

**Comment by Sophist-UK** [comment]
Functional tests using file below work fine. Initial performance test on Teddy Bear (or toy dog) file, are very positive.

Code submitted for review. Full performance tests to follow tomorrow (assuming that Inner First ever completes on the old code for this big file).

[test cut inside.zip](https://github.com/meerk40t/meerk40t/files/7573558/test.cut.inside.zip)

**Comment by tatarize** [comment]
Any commits to this will waste 6 hours of unit-testing broken mac.

**Review by tatarize — DISMISSED** [review]
Cannot be approved until any commit doesn't waste a ton of resources.

**Review by tatarize — APPROVED** [review]

**Comment by tatarize** [comment]
Even if broken. Any updates should be done in a different PR to prevent hours of wasted resources.

**Comment by Sophist-UK** [comment]
I disabled the unittest workflow.

**Comment by Sophist-UK** [comment]
And I don't get what the issue is and why it only applies to further commits and not to the base PR.

**Comment by Sophist-UK** [comment]
Might be that this has broken a unittest and that goes into a loop. I will take a look.

**Comment by Sophist-UK** [comment]
1. Teddy, Pre PR, no travel opt, one pass, merge operations:

[00:45:03] Executing Inner-First Identification
[00:45:03] Length at start: 2650756 mils
[00:59:33] Length at end: 2663592 mils (0%), optimized in 870.431 elapsed seconds using 849.938 seconds CPU
[00:59:33] Executing Inner Selection-Only optimization
[00:59:33] Length at start: 2663592 mils
[00:59:33] Length at end: 2663630 mils (0%), optimized in 0.226 elapsed seconds using 0.141 seconds CPU in 6 iterations

2. With this PR, no travel opt, one pass, merge operations

[09:33:04] Executing Inner-First Identification
[09:33:14] Inner paths identified in 9.733 elapsed seconds using 9.484 seconds CPU
[09:33:14] Executing Inner Selection-Only optimization
[09:33:14] Length at start: 2650756 mils
[09:33:14] Length at end: 2638180 mils (-0%), optimized in 0.273 elapsed seconds using 0.203 seconds CPU in 6 iterations

3. With this PR, with travel opt, one pass, merge operations

[09:36:58] Executing Inner-First Identification
[09:37:12] Inner paths identified in 13.413 elapsed seconds using 13.031 seconds CPU
[09:37:12] Executing Greedy Short-Travel optimization
[09:37:12] Length at start: 2650756 mils
[09:38:10] Length at end: 80314 mils (-97%), optimized in 57.845 elapsed seconds using 56.609 seconds CPU

4. With this PR, with travel opt, three passes, merge all

[09:39:40] Executing Inner-First Identification
[09:40:03] Inner paths identified in 22.865 elapsed seconds using 21.828 seconds CPU
[09:40:03] Executing Greedy Short-Travel optimization
[09:40:03] Length at start: 2650756 mils
[09:41:26] Length at end: 82914 mils (-97%), optimized in 82.638 elapsed seconds using 79.547 seconds CPU

**Comment by Sophist-UK** [comment]
I ran the unit tests just fine on my PC. I am guessing that this is an issue with unit tests on a mac. I don't have a mac so I can't test this locally but I will try to see why it hangs on a mac from the workflow output.

The only changes I now want to make to this are to the tooltips to reflect that this is no longer so CPU intensive.

**Pull request merged**
