### PR TITLE
Fix resize by < 10%...

### PR DESCRIPTION
**Pull request by Sophist-UK**
... plus useful advisory messages plus fix rescale of remaining elements still happening when some images are locked.

### CODE REVIEW

**Comment by Sophist-UK** [comment]
As an aside I note that the following happens if you switch focus away from Meerk40t and back whilst the cursor is in one of th position panel fields - selected items move by 0.000069mm in x direction and 0.000015mm in y direction each time. This is another (admittedly very minor) bug.
```
[10:13:25] resize 27.096849mm 6.000237mm 265.809638mm 208.000000mm
[10:13:27] resize 27.096918mm 6.000252mm 265.809638mm 208.000000mm
[10:13:32] resize 27.096987mm 6.000267mm 265.809638mm 208.000000mm
[10:13:45] resize 27.097056mm 6.000282mm 265.809638mm 208.000000mm
[10:17:19] resize 27.097125mm 6.000297mm 265.809638mm 208.000000mm
[10:17:39] resize 27.097194mm 6.000312mm 265.809638mm 208.000000mm
```

**Comment by Sophist-UK** [comment]
Ok I fixed the spurious resizes and cleaned up the code a little too.

**Review by tatarize — APPROVED** [review]
I somewhat prefer less drastic looking diffs but it clearly fixes the weird error.

**Comment by Sophist-UK** [comment]
I don't think the diffs are that drastic!!

**Pull request merged**
