### PR TITLE
Add link to beginners wiki

### PR DESCRIPTION
**Pull request by Sophist-UK**
@tatarize  - I have no idea what is causing it, but this change stops the webhelp functionality from launching a web page.

Works on master branch, doesn't work on this branch.

Can you help?

### CODE REVIEW

**Comment by tatarize** [comment]
Remove requests from the import there it fails. All the routines that work like mini-plugins do not load if there's an import error. So the dxf-loading stuff will fail if ezdxf fails, and this means that it does not load. So it just silently removes DXF functions. The same is happening here. the `import requests` line that suddenly shows up there is suffering an import error which aborts loading the plugin.

**Comment by Sophist-UK** [comment]
Ah. No error message even when there is an attached console. Usually you run without an attached console so such messages will not be seen by the user.

That was a line I left in for making the Github API requests.

**Comment by Sophist-UK** [comment]
Or at least do so when developer mode is on.

**Review by tatarize — APPROVED** [review]
Perfectly fine set of changes. No potential bugs. That formatting will likely get undone by applying Black tho.

**Comment by Sophist-UK** [comment]
No - the black code check did not pick up anything new. Just the existing 3 issues.

**Comment by Sophist-UK** [comment]
Default black line length is 88 and is not overridden. I will need to adjust all other tools to use the same line length,

Also, I am going to look at switching to pyproject.toml as a common configuration file if that is OK with you.

How much checking do you want to happen on the unittest .py files?

**Comment by tatarize** [comment]
I'm mostly concerned with the code and features set, how it's setup on github etc doesn't matter that much to me, so long as it can still upload to pypi, I'm fine with such things.

**Pull request merged**
