### PR TITLE
Configure Github repo settings for ...

### PR DESCRIPTION
**Pull request by Sophist-UK**
...

1. Default PR reviewers
2. Code of Conduct
3. Simple PR Guidelines (for new contributors)
4. Simple Issue template
5. How to request support
6. New style bug/suggestion issue templates. (Currently as an alternative to 4. with a view of removing 4. once these are shown to be working.)

Inspired by coming across https://github.com/Josee9988/project-template/tree/master/.github

Whilst the templates can be viewed in [Files changed](meerk40t/meerk40t/pull/743/files), they cannot be tested until they are merged.

### CODE REVIEW

**Comment by tatarize** [comment]
@joerlane Can you abide by these. CoC too onerous?

**Comment by tatarize** [comment]
Joe can't really see his way through the CoC. Maybe pull that out for now and most of the rest are fine.

**Comment by Sophist-UK** [comment]
Ok - I have redrafted the Code of Conduct to be much less PC.

But this version is only my own viewpoint. Please feel free to add your own edits here (or send them anonymously to Tatarize for him to post on your behalf.

**Review by tatarize — APPROVED** [review]
You could even put back most of the original CoC if you want. Mostly paiin doesn't like accepting rules.

**Comment by Sophist-UK** [comment]
Actually I think I prefer the current one. The original CoC was too politically correct and too officious IMO.

**Pull request merged**
