### PR TITLE
Fixes Nuke-Beta2 Crash bug.

### PR DESCRIPTION
**Pull request by tatarize**
* Prevents rastercut from being considered by the group expecting code.
* Adds first for rastercut, so it's considered in ordering for distances in new mode.

### CODE REVIEW

**Comment by Sophist-UK** [comment]
Apologies for the raster bug!!

**Comment by Sophist-UK** [comment]
Do you want to wait for beta3 until I diagnose the other (**non**-crashing) bug?

**Review by Sophist-UK — APPROVED** [review]

**Comment by tatarize** [comment]
This should be fairly good enough. I think I got the non-crashing bug. Or rather made it work.

**Comment by tatarize** [comment]
@Sophist-UK was there something else you wanted addressed before pushing out Beta3?

**Comment by Sophist-UK** [comment]
Beta3 is urgent because of my bad. 

The two changes I want to make are not crashing things so less urgent and I cannot get to them until later. They will need to wait until Beta4 I think.

The bug in #767 still exists and will take some tracking down.

And the performance improvements can also wait.

**Comment by tatarize** [comment]
Ah. Okay. I'm fine with additional betas. There's still a good amount of life in the 0.7.x line for features since I'm a bit better at merging in 0.8.0 than I was in 0.6.x 0.7.x divide. So features like ConsoleOp are easier to filter up to the higher levels of code. Just checking mostly against crashing and burning and slightly missed the mark on that one. All's well though.

**Comment by Sophist-UK** [comment]
@tatarize Thanks for fixing this though.

**Pull request merged**
