### PR TITLE
0.5.2 - More Usability

### PR DESCRIPTION
**Pull request by tatarize**

### CODE REVIEW

**Comment by tatarize** [comment]
- [ ] Refresh when adding interrupt to Jobs.
- [ ] Jobs elements to be able to rearrange and delete, items.
- [ ] New Select Mode stuff to work correctly with rearranging.
- [ ] Custom 1-5 hotkeys not to overwrite the hotkeys themselves.
- [ ] Single capture for tree and scene hotkeys.
- [ ] Do not break the function of the arrow keys in the tree menu.
- [ ] Implement TraceJob Simple
- [ ] Implement TraceJob ConvexHull

---

May be pushed to next version.

- [ ] Transformation editor.

**Comment by joerlane** [comment]
Bug Reports: 

SVG file with a single black filled path acts like there is no job to run. Attempting to run it will simply home the machine; it does not move to the position of the object. A file with two objects does function. This can also be reproduced inside MeerK40t by deleting other objects until only one raster operation on a vector path remains. 

Element properties dialogs open without being in focus. So typing numbers does not register without clicking inside of the dialog (despite the speed being highlighted on open).

**Comment by tatarize** [comment]
Most likely an issue with raster jobs of 1 object that is a image being proper raster jobs and other jobs needing to be made into those. In that case the 1 object thing passes but it can't raster the vector without the conversion.

**Comment by tatarize** [comment]
- Test Basic17 multipass progressive gap issue. 
- Test MeerK40t online, machine turned off and back on, reclaim of interface.

**Comment by tatarize** [comment]
- [ ] Implement go-to in navigation.

**Comment by tatarize** [comment]
This should make the perspective bit work for the camera with all the required adjustments, and zoom and pan. It's plausibly a full camera functionality for MeerK40t. The switch to GC full should make MeerK40t fully functional for wxPython 4.0.x rather than require 4.1 and the snapshot builds. (Needs testing).

**Comment by tatarize** [comment]
Okay, to publish 0.5.2 I'm going to table the feature additions and just finish tackling the bugs.

**Comment by tatarize** [comment]
- [ ] Mac auto scroll issue with forced select.

**Comment by tatarize** [comment]
- [ ] Attribute errors in dxf support #41. This known crash bugs should be fixed.

**Comment by joerlane** [comment]
Small crash on the GRBL testing when attempting to start a job, and a failure to home (error 20\r\n reported in that case):

b"Grbl 1.1e ['$' for help]\r\n"
Processing Gcode: b'G0\n'
b'ok\r\n'
Processing Gcode: b'G21 G90 ; mm, absolute\nG1 Z60 F1250 S0 ; Z to top\nG28.3Z50 ; set Z pos\nG28.2XY ; Home XY\nM911 G4P0.1\nM912 G4P0.05\nM911 G4P0.1\nM912\n'
b'error:20\r\n'
Processing Gcode: b'?\n'
Exception in thread ServerThread:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/home/pi/Documents/meerk40t/LaserServer.py", line 49, in run
    self.server.pipe.write(data_from_socket)
  File "/home/pi/Documents/meerk40t/DefaultModules.py", line 218, in write
    self.read_info = "error:%d\r\n" % cmd
TypeError: %d format: a number is required, not NoneType

**Pull request merged**
