### PR TITLE
Fix ansi check on windows 8.1, add dark theme support

### PR DESCRIPTION
**Pull request by Sophist-UK**
1. Fixes windows version detection and avoids crash on Windows 8.1 and handles Windows 11.
2. Handles darkmode colours (as reported by @joerlane .

### CODE REVIEW

**Comment by tiger12506** [comment]
I'm fine with this, it makes sense. Has anyone checked if the WinDLL change still works from within a build? Or is that what I'm supposed to be checking?

**Comment by Sophist-UK** [comment]
Sorry Tiger. In the issue user is still diagnosing the solution. My fault for not marking this draft.

**Comment by Sophist-UK** [comment]
Bump

**Comment by Sophist-UK** [comment]
This is good to go. The actual change to how we load the dll needs to be in a different PR.

**Review by tatarize — APPROVED** [review]

**Comment by Sophist-UK** [comment]
Should be good for review again now. Foreground colours are now correct on Linux (and should be OK on Mac too). Also done something with scroll bars but I could not recreate the scrolling issue that @tiger12506 reported so we will need to see if this fixes that.

**Comment by Sophist-UK** [comment]
If this doesn't completely fix @tiger12506 's scroll issue, I suggest that it is merged anyway as it is much closer than before.

**Review by tiger12506 — DISMISSED** [review]
This seems to have fixed the issues I experienced. Nice work.

**Review by tatarize — APPROVED** [review]

**Pull request merged**
