### PR TITLE
Fix Codecy Checks with Pylint Disables

### PR DESCRIPTION
**Pull request by tatarize**
https://pylint.pycqa.org/en/latest/user_guide/message-control.html

Using fine grained pylint to disable issues with dynamically created attributes

### CODE REVIEW

**Review by Sophist-UK — DISMISSED** [review]

**Comment by tatarize** [comment]
Sleep changes codecy wanted might be a bit weirder, should allow better understanding of typing but might require the pylint turned off.

**Comment by tatarize** [comment]
Fine grain disable didn't seem to work.

**Comment by tatarize** [comment]
Nah, we can just disable the bits. It doesn't say it's corrected. But it didn't refind the error. So it's sort of lag or something.

**Comment by tatarize** [comment]
I can't tell if codecy managed to disable these things with the pylint calls. Seems like it should have but I don't see them removed as issues.

**Comment by tatarize** [comment]
@Sophist-UK This would need re-approval, then I could merge those changes upstream. It also helps keeping versions like services branch nicely together.

**Review by Sophist-UK — APPROVED** [review]
I am approving this only on the basis that it is Tat's as I have no idea what it does and cannot really review it properly. Also I have concerns that some of the black reformatting may result in other PRs failing to merge.

**Comment by tatarize** [comment]
@Sophist-UK I updated the blindalias pr to merge.

**Pull request merged**
