### PR TITLE
Make Processed Images Uniform

### PR DESCRIPTION
**Pull request by tatarize**
Seeks to make rasters uniform.  Should get rid of any and all whack-a-mole style errors here. Should simplify the understanding. Conceptually this takes alpha into account and uses it to generate a greyscale `L` image. This should be the result of any actualize operation. The core idea behind this technology is displaying the black and white as black and transparent. This is done by using the black and white image as the alpha-mask of a pure black image and displaying that. Then under the hood, all images that with any processing are greyscale. If the image is not `L` to start, we peel off the alpha and combine that with the image to make alpha values entirely white. 

* All the raster stuff is transitioned to using dewhite to make the preview images. This includes images that are full color and are not changed. They are merely displayed in black and transparent. 
* All images are actualized and (should-be) Raster Wizard'ed to black/transparent images. The viewed bitmap is automatically converted regardless of the original mode of the image.
* Black/Transparent images are stored in `mode L` image, which is properly black and white but viewed as black/transparent.
* Actualize makes the images actually black and transparent, and crops the size correctly.
* Has been extensively checked with RasterWizard.
* Has been tested for inverted images and inverted images might prefer being white/transparent images.

### CODE REVIEW

**Comment by Sophist-UK** [comment]
> I'm biased but I think we should consider \[this one over #600\].

I am not biased and I have no issues considering #601 vs #600.

I will need to try this code against my test cases, but I wonder whether:

a. We should reduce coloured images to greyscale every time - I have no idea either way but I shied away from going this far with my code but if you think it is OK, then it is fine with me;
b. If we are converting to "L", whether the code should mimic the greyscale code in RasterScripts;
c. Whether we should aim for an LA mode which preserves alpha rather than convert transparent to white (which I would personally like to see because you don't end up with white background overlaying other elements);
d. Whether the mask code is correct `255 - e` rather than `255 if e == 0 else 0`
e. Whether #601 addresses some of the stuff that I think still needs fixing as described above.

Perhaps we should combine the best of both.

**Comment by tatarize** [comment]
Discussion on #599

**Comment by tatarize** [comment]
Responded in the issue #599 (trying to keep things organized)

**Comment by Sophist-UK** [comment]
Looking good except some minor stuff:
1. After right-click actualise, scene is not updated with cropped image size.
2. In raster wizard Gravy, with `grayscale` **disabled** and `tone` enabled there are some light gray artifacts showing in the Heather Stone image.

Otherwise looking very good!!!!

Once again you have proven your coding awesomeness!!

**Pull request merged**
