### PR TITLE
Improve Lhystudios config window

### PR DESCRIPTION
**Pull request by Sophist-UK**
1. Text and tooltips
2. Layout
3. Integer spin boxes

### CODE REVIEW

**Comment by Sophist-UK** [comment]
# Before
image

# After
image

**Comment by tatarize** [comment]
No real objections here though the work might be short lived since there's a shift in the config window for 0.8.0 to work more with panes since they are easier to disable and enable and to cover all the different features.

page1controller

page2controller

**Comment by tatarize** [comment]
The shift home position isn't in pixels, it's actually in steps. Though really in 0.8.0 it needs to take a physical unit measurement there to work correctly since raw units are going to be nanometers.

**Comment by Sophist-UK** [comment]
Yes - though some of this will translate to the new settings.

I thought I was thinking ahead by switching from mils to px (by which I meant steps) but I can revert this easily enough.

**Comment by Sophist-UK** [comment]
P.S. I still plan to try to create a more standardised way of creating dialog boxes / panes - and this was part of the learning curve.

**Comment by tatarize** [comment]
There's PropertyPanels these are used here and there and create panels for choices. So if I make a quickie dialog to change values stored in a choice you can call a PropertyPanel to do that. Any more standardized methods I would think should fall into that sort of thing.

**Comment by tatarize** [comment]
Strict isn't a programmed speed mode, it's actually makes sure the directionality of the start of the vector cut comes from the TOP-LEFT always rather than going the typical and correct direction.

**Comment by Sophist-UK** [comment]
I based the Strict description on the previous tooltip. Happy to use any text that helps a non-technical user decide whether to check the option or not. What are the symptoms that they might get that should prompt them to check this option?

**Comment by tatarize** [comment]
https://github.com/meerk40t/meerk40t/blob/tatarize-services/meerk40t/gui/operationpropertymain.py

Might be worth looking at for tooltips. The core idea being to keep them together in larger triple quoted areas rather than stick them together in longer areas. There's a very real chance that somebody won't need to translate the entire tooltip so keeping it together may be for the best.

**Review by tatarize — APPROVED** [review]

**Pull request merged**
